from bd import *
from funciones_captura import leer_entero

database = "g10.db"

# Crear una conexión a la base de datos
conn = create_connection(database)

if conn is not None:
    create_table(conn)
    #inserta todos los estudiantes de G10
    
    insert_estudiante(conn, ('Stiven Josue','Diaz Crespo','stiven.diaz.talentotech@usa.edu.co','M','3026574653'))
    insert_estudiante(conn, ('Jose Smith','Santamaria Rodriguez','jose.santamaria.talentotech@usa.edu.co','M','3158108209'))
    insert_estudiante(conn, ('Esmeralda','Moya Forero','esmeralda.moya.talentotech@usa.edu.co','F','3213942643'))
    insert_estudiante(conn, ('Juan Camilo','Zamora','juan.zamora.talentotech@usa.edu.co','M','3192034943'))
    insert_estudiante(conn, ('Nelson Fernando','Vallejos Bastidas','nelson.vallejos.talentotech@usa.edu.co','M','3154107618'))
    insert_estudiante(conn, ('Gina Liseth','Garcia Segura','gina.garcia.talentotech@usa.edu.co','F','3194447604'))
    insert_estudiante(conn, ('Sara Valentina','Caicedo Duarte','sara.caicedo.talentotech@usa.edu.co','F','3142301572'))
    insert_estudiante(conn, ('Carlos','Diaz','carlos.diaz.talentotech@usa.edu.co','M','3018238390'))
    insert_estudiante(conn, ('Diego Mauricio','Ortiz Zapata','diego.ortiz.talentotech@usa.edu.co','M','3135025656'))
    insert_estudiante(conn, ('antonia','salamanca','antonia.correa.talentotech@usa.edu.co','F','3112100113'))
    insert_estudiante(conn, ('Andres Felipe','Moreno Zambrano','andres.moreno.talentotech@usa.edu.co','M','3103175157'))
    insert_estudiante(conn, ('Yessica','Moreno Orjuela','yessica.moreno.talentotech@usa.edu.co','F','3208001145'))
    insert_estudiante(conn, ('Julian Esteban','Motavita Lopez','julian.otavita.talentotech@usa.edu.co','M','3107695598'))
    insert_estudiante(conn, ('José Abel','Méndez Cárdenas','jose.mendez.talentotech@usa.edu.co','M','3112286738'))
    insert_estudiante(conn, ('Yeimy Beronica','Valero Cifuentes','yeimy.valero.talentotech@usa.edu.co','F','3506773025'))
    insert_estudiante(conn, ('Pedro Santiago','Álvarez Cárdenas','pedro.alvarez.talentotech@usa.edu.co','M','3118233766'))
    insert_estudiante(conn, ('sharon andrea','sabogal guevara','sharon.sabogal.talentotech@usa.edu.co','F','3132057903'))
    insert_estudiante(conn, ('Jose Luis','Venegas Landinez','jose.venegas.talentotech@usa.edu.co','M','3144223044'))
    insert_estudiante(conn, ('Claudia Janeth','Sánchez Pulido','claudia.sanchez.talentotech@usa.edu.co','F','3207899455'))
    insert_estudiante(conn, ('Edwin Antonio','Hernandez Monsalve','edwin.hernandez.talentotech@usa.edu.co','M','3142814067'))
    insert_estudiante(conn, ('David Santiago','Jiménez Santamaría','david.jimenez.talentotech@usa.edu.co','M','3112169145'))
    insert_estudiante(conn, ('John','Tula','john.tula.talentotech@usa.edu.co','M','3213471835'))
    insert_estudiante(conn, ('Brayan Steven','Hilarión Torres','brayan.hilarion.talentotech@usa.edu.co','M','3202419416'))
    insert_estudiante(conn, ('Edwin Camilo','Cruz Jimenez','edwin.cruz01.talentotech@usa.edu.co','M','3214024201'))
    insert_estudiante(conn, ('Camilo Andrés','García Ducuara','camilo.garcia01.talentotech@usa.edu.co','M','3057918062'))
    insert_estudiante(conn, ('Luis Felipe','Jiménez Cristiano','luis.jimenez.talentotech@usa.edu.co','M','3502052725'))
    insert_estudiante(conn, ('Adrian Ricardo','Herrera Supelano','adrian.herrera.talentotech@usa.edu.co','M','3125273627'))
    insert_estudiante(conn, ('Juan Camilo','Barrera Puerto','juan.barrera.talentotech@usa.edu.co','M','3212192839'))
    insert_estudiante(conn, ('Angela Liseth','Barrera Gonzalez','angela.barrera.talentotech@usa.edu.co','F','3115359109'))
    insert_estudiante(conn, ('Derly Andrea','Marín Jiménez','derly.marin.talentotech@usa.edu.co','F','3234269786'))
    insert_estudiante(conn, ('Jersson Sebastián','Hernández Mateus','jersson.hernandez.talentotech@usa.edu.co','M','3195230886'))
    insert_estudiante(conn, ('Wilmer Stiven','Prada Rodriguez','wilmer.prada.talentotech@usa.edu.co','M','3219220053'))
    insert_estudiante(conn, ('Deisy Lorena','Lancheros Varela','deisy.lancheros.talentotech@usa.edu.co','F','3224404555'))
    insert_estudiante(conn, ('Diego Oswaldo','Corredor Yagama','diego.corredor.talentotech@usa.edu.co','M','3103265973'))
    insert_estudiante(conn, ('Johan Stiven','Quiñones Delgadillo','johan.quinones.talentotech@usa.edu.co','M','3226475072'))
    insert_estudiante(conn, ('Yenny Estefania','Gómez Corredor','yenny.gomez.talentotech@usa.edu.co','F','3156947292'))
    insert_estudiante(conn, ('Moises Eduardo','Varela Almario','moises.varela.talentotech@usa.edu.co','M','3127394080'))
    insert_estudiante(conn, ('Jelen Johana','Orjuela Linares','jelen.orjuela.talentotech@usa.edu.co','F','3205070310'))
    insert_estudiante(conn, ('Diana Paola','Lopez Avendaño','diana.lopez.talentotech@usa.edu.co','F','3116452684'))
    insert_estudiante(conn, ('Cristian','Rodríguez','cristian.rodriguez04.talentotech@usa.edu.co','M','3208575989'))
    insert_estudiante(conn, ('Haider','Cardenal','haider.cardenal.talentotech@usa.edu.co','M','3219413074'))
    insert_estudiante(conn, ('Angélica Yuriza','Cardenal Cuchivague','angelica.cardenal.talentotech@usa.edu.co','F','3046701521'))
    insert_estudiante(conn, ('Juan David','Rivera Peña','juan.rivera01.talentotech@usa.edu.co','M','3203081179'))
    insert_estudiante(conn, ('Alejandra','Herrera Mariño','alejandra.herrera.talentotech@usa.edu.co','F','3212821265'))
    insert_estudiante(conn, ('lorena','guarin','claudia.guarin.talentotech@usa.edu.co','F','3178458356'))
    insert_estudiante(conn, ('José Sebastián','Lara Barón','jose.lara.talentotech@usa.edu.co','M','3123547674'))
    insert_estudiante(conn, ('Adriana','Romero Tovar','adriana.romero.talentotech@usa.edu.co','F','3017282600'))
    insert_estudiante(conn, ('Daniel Sneider','Novoa Puentes','daniel.novoa.talentotech@usa.edu.co','M','3209475552'))
    insert_estudiante(conn, ('Karen Dayana','Manrique Bello','karen.manrique.talentotech@usa.edu.co','F','3217159004'))
    insert_estudiante(conn, ('Claudia Ximena','Cepeda Guayacundo','claudia.cepeda.talentotech@usa.edu.co','F','3232164744'))
    insert_estudiante(conn, ('Olga Susana','Gutiérrez Bernal','olga.gutierrez.talentotech@usa.edu.co','F','3228428125'))
    insert_estudiante(conn, ('Elkin Augusto','Mora Martinez','elkin.mora.talentotech@usa.edu.co','M','3125081160'))
    insert_estudiante(conn, ('Jhon Jairo','Gonzalez Sichaca','jhon.gonzalez02.talentotech@usa.edu.co','M','3172695552'))
    insert_estudiante(conn, ('Luna Mariana','Cagua Clavijo','luna.cagua.talentotech@usa.edu.co','F','3229028600'))
    insert_estudiante(conn, ('Julieth Vanessa','Peña Piedrahíta','julieth.pena.talentotech@usa.edu.co','F','3154613737'))
    insert_estudiante(conn, ('Axly Stephanie','Ospina Romero','axly.ospina.talentotech@usa.edu.co','F','3209624273'))
    insert_estudiante(conn, ('Wilson Abel','Holguin Ariza','wilson.holguin.talentotech@usa.edu.co','M','3045932403'))
    insert_estudiante(conn, ('Andrea Valeria','Aldaz Palacios','andrea.aldaz.talentotech@usa.edu.co','F','3507024818'))
    insert_estudiante(conn, ('juan diego','camargo','juan.camamrgo.talentotech@usa.edu.co','M','3112606176'))
    insert_estudiante(conn, ('Maria Catalina','Castro Camacho','maria.castro03.talentotech@usa.edu.co','F','3008707309'))
    insert_estudiante(conn, ('Jose','Sosa','jose.sosa.talentotech@usa.edu.co','M','3188830517'))
    insert_estudiante(conn, ('Mayerly Caterine','Gutierrez Maldonado','mayerly.gutierrez.talentotech@usa.edu.co','F','3232833423'))
    insert_estudiante(conn, ('Valery','Chaves Pérez','valery.chaves.talentotech@usa.edu.co','F','3113433518'))
    insert_estudiante(conn, ('ana paola','rodriguez pachon','ana.rodriguez01.talentotech@usa.edu.co','F','3108865392'))
    insert_estudiante(conn, ('Cristian David','Cedano Melo','cristian.cedano.talentotech@usa.edu.co','M','3202717272'))
    insert_estudiante(conn, ('Daniel Camilo','Cruz Cárdenas','daniel.cruz.talentotech@usa.edu.co','M','3112141066'))
    insert_estudiante(conn, ('Diana Lucelly','Ramírez Ramírez','diana.ramirez01.talentotech@usa.edu.co','F','3123959737'))
    insert_estudiante(conn, ('Jorge','Morales','jorge.morales01.talentotech@usa.edu.co','M','3118624432'))
    insert_estudiante(conn, ('Juan David','Sandoval Bello','juan.sandoval02.talentotech@usa.edu.co','M','3193813361'))
    insert_estudiante(conn, ('Oscar David','Peña Garavito','oscar.pena01.talentotech@usa.edu.co','M','3202813399'))
    insert_estudiante(conn, ('Yessica Alexandra','Lozano Pabón','yessica.lozano.talentotech@usa.edu.co','F','3212161903'))
    insert_estudiante(conn, ('ANDERSON FERNEY','PEÑA ANGEL','anderson.pena.talentotech@usa.edu.co','M','3123294594'))
    insert_estudiante(conn, ('Carla Gicela','López Daza','carla.lopez.talentotech@usa.edu.co','F','3222938823'))
    insert_estudiante(conn, ('Diana Patricia','Toledo Herrera','diana.toledo.talentotech@usa.edu.co','F','3152171340'))
    insert_estudiante(conn, ('Juliana','Valencia Pinilla','juliana.valencia.talentotech@usa.edu.co','F','3143945784'))
    insert_estudiante(conn, ('Leidy Katherine','Rincon Rodriguez','leidy.rincon.talentotech@usa.edu.co','F','3214239319'))
    insert_estudiante(conn, ('Diana Lorena','Ojeda Gomez','diana.ojeda.talentotech@usa.edu.co','F','3147998146'))
    insert_estudiante(conn, ('Luis Felipe','Hernández Zambrano','luis.hernandez01.talentotech@usa.edu.co','M','3124665549'))
    insert_estudiante(conn, ('Andrés','Juzga','andres.juzga.talentotech@usa.edu.co','M','3144253728'))
    insert_estudiante(conn, ('Miguel','Lopez','miguel.lopez01.talentotech@usa.edu.co','M','3124624003'))
    insert_estudiante(conn, ('Gissell Viviana','Rojas Segura','gissell.rojas.talentotech@usa.edu.co','F','3124822898'))
    insert_estudiante(conn, ('Charles Erasmo','Daza Malagon','cedaza@mintic.gov.co','M','3103257236'))
    
    #listar los estudiantes
    select_all_estudiantes(conn)

    #capturar datos del estudiante

    #idEstudiante = leer_entero("Ingresa el id del estudiante?\n","Debes ingresar el id del estudiante🤖")
    #select_estudiante(conn,idEstudiante)
