from bd import *

database = "g11.db"

# Crear una conexión a la base de datos
conn = create_connection(database)

if conn is not None:
    create_table(conn)
    #inserta todos los estudiantes de G10
    insert_estudiante(conn, ('María Camila','Villarraga Pineda','maria.villarraga.talentotech@usa.edu.co','F','3123239480'))
    insert_estudiante(conn, ('Luis Carlos','Muñoz Lopez','luis.munoz.talentotech@usa.edu.co','M','3223476903'))
    insert_estudiante(conn, ('Juan Pablo','Ortiz Castillo','juan.ortiz.talentotech@usa.edu.co','M','3178229035'))
    insert_estudiante(conn, ('Karen Yessenia','Jiménez López','karen.jimenez.talentotech@usa.edu.co','F','3132632125'))
    insert_estudiante(conn, ('Maria Edilma','Cardozo Tique','maria.cardozo.talentotech@usa.edu.co','F','3132316531'))
    insert_estudiante(conn, ('Fernando','Palacios Torres','fernando.palacios.talentotech@usa.edu.co','M','3138828806'))
    insert_estudiante(conn, ('Zharick Michelle','Fetecua Huertas','zharick.fetecua.talentotech@usa.edu.co','F','3122590428'))
    insert_estudiante(conn, ('Camilo Antonio','Pacheco Ordoñez','camilo.pacheco.talentotech@usa.edu.co','M','3124441596'))
    insert_estudiante(conn, ('Santiago','Mahecha Pérez','santiago.mahecha.talentotech@usa.edu.co','M','3204893814'))
    insert_estudiante(conn, ('Robinson Yhesid','Rincon Bernal','robinson.rincon.talentotech@usa.edu.co','M','3002891319'))
    insert_estudiante(conn, ('Jefferson','Escobar','jefferson.escobar.talentotech@usa.edu.co','M','3156452884'))
    insert_estudiante(conn, ('Jorge Enrique','Guerrero Ruiz','jorge.guerrero.talentotech@usa.edu.co','M','3112499410'))
    insert_estudiante(conn, ('William','Martín Mendez','william.martin.talentotech@usa.edu.co','M','3024790656'))
    insert_estudiante(conn, ('Leiver Santiago','Cruz Herrera','leiver.cruz.talentotech@usa.edu.co','M','3204873370'))
    insert_estudiante(conn, ('Santiago','Amaya Cetina','santiago.amaya.talentotech@usa.edu.co','M','3103194939'))
    insert_estudiante(conn, ('Rafael Enrique','Martínez Méndez','rafael.martinez.talentotech@usa.edu.co','M','3144535491'))
    insert_estudiante(conn, ('Wilson','Serrato Garzón','wilson.serrato.talentotech@usa.edu.co','M','3196832654'))
    insert_estudiante(conn, ('Maria Camila','Polania Betancourt','maria.polania.talentotech@usa.edu.co','F','3212213907'))
    insert_estudiante(conn, ('Maryann Alejandra','López Riaño','maryann.lopez.talentotech@usa.edu.co','F','3125734180'))
    insert_estudiante(conn, ('MARCO AURELIO','CORDON SILVA','marco.cordon.talentotech@usa.edu.co','M','3174601398'))
    insert_estudiante(conn, ('Dairo Alvaro','Hurtado Hurtado','dairo.hurtado.talentotech@usa.edu.co','M','3143350364'))
    insert_estudiante(conn, ('Wilmer Stick','Rueda Molina','wilmer.rueda.talentotech@usa.edu.co','M','3102405565'))
    insert_estudiante(conn, ('Maria','Toro','maria.toro.talentotech@usa.edu.co','F','3002669928'))
    insert_estudiante(conn, ('nini johana','diaz martinez','nini.diaz.talentotech@usa.edu.co','F','3208734778'))
    insert_estudiante(conn, ('Sandra Milena','Campos Zabala','sandra.campos.talentotech@usa.edu.co','F','3115379460'))
    insert_estudiante(conn, ('Julio Roberto','Zambrano Cordoba','julio.zambrano.talentotech@usa.edu.co','M','3208295592'))
    insert_estudiante(conn, ('Javier Eduardo','Ojeda Naranjo','javier.ojeda.talentotech@usa.edu.co','M','3214571625'))
    insert_estudiante(conn, ('Camilo Orlando','Angarita Baracaldo','camilo.angarita.talentotech@usa.edu.co','M','3112127448'))
    insert_estudiante(conn, ('Oscar Javier','Sotelo Corredor','oscar.sotelo.talentotech@usa.edu.co','M','3118520708'))
    insert_estudiante(conn, ('Leidy Lorena','Parra Ruiz','leidy.parra01.talentotech@usa.edu.co','F','3228339628'))
    insert_estudiante(conn, ('Duvan Estiven','Guarnizo Medina','duvan.guarnizo.talentotech@usa.edu.co','M','3046242657'))
    insert_estudiante(conn, ('Maicol Iván','Coronado Gómez','maicol.coronado.talentotech@usa.edu.co','M','3108725109'))
    insert_estudiante(conn, ('Vivier Aldair','Campo','vivier.campo.talentotech@usa.edu.co','F','3208531137'))
    insert_estudiante(conn, ('Yoseph Santiago','Mesa Sierra','yoseph.mesa.talentotech@usa.edu.co','M','3204599335'))
    insert_estudiante(conn, ('Alejandra Saile','Lenes Beltrán','alejandra.lenes.talentotech@usa.edu.co','F','3205474587'))
    insert_estudiante(conn, ('Duvan Stiven','Triana Miranda','duvan.triana.talentotech@usa.edu.co','M','3209981780'))
    insert_estudiante(conn, ('Iovanna Alicia','Ramírez Forero','iovanna.ramirez.talentotech@usa.edu.co','F','3108729678'))
    insert_estudiante(conn, ('Vanessa Liliana','Sarabia Vargas','vanessa.sarabia.talentotech@usa.edu.co','F','3116534000'))
    insert_estudiante(conn, ('Caren Liceth','Amaya Torres','caren.amaya.talentotech@usa.edu.co','F','3102719251'))
    insert_estudiante(conn, ('Brayan Fabian','Silva Romero','brayan.silva.talentotech@usa.edu.co','M','3133028271'))
    insert_estudiante(conn, ('Karen Tatiana','Rojas Medina','karen.rojas02.talentotech@usa.edu.co','F','3162906617'))
    insert_estudiante(conn, ('Luis Carlos','Rico Gonzalez','luis.rico.talentotech@usa.edu.co','M','3118000508'))
    insert_estudiante(conn, ('Andrei Jeancarlo','Carreño Rodriguez','andrei.carreno.talentotech@usa.edu.co','M','3183065829'))
    insert_estudiante(conn, ('Leidy Johana','Guerrero Buitrago','leidy.guerrero.talentotech@usa.edu.co','F','3123831295'))
    insert_estudiante(conn, ('Jeiser Jose','Barrios Madera','jeiser.barrios.talentotech@usa.edu.co','M','3024131210'))
    insert_estudiante(conn, ('Carlos Arturo','Castelblanco Perez','carlos.castelblanco.talentotech@usa.edu.co','M','3223059230'))
    insert_estudiante(conn, ('David Alejandro','Guevara Morantes','david.guevara.talentotech@usa.edu.co','M','3118859052'))
    insert_estudiante(conn, ('Viviana Carolina','Garzon Cortes','viviana.garzon.talentotech@usa.edu.co','F','3228570060'))
    insert_estudiante(conn, ('José Harbey','Avendaño Reyes','jose.avendano.talentotech@usa.edu.co','M','3192167401'))
    insert_estudiante(conn, ('Daniel Stiven','Forero Mateus','daniel.forero.talentotech@usa.edu.co','M','3123517559'))
    insert_estudiante(conn, ('Kevin Johan','Moreno Moreno','kevin.moreno.talentotech@usa.edu.co','M','3138051185'))
    insert_estudiante(conn, ('Edier Alejandro','Acevedo Parra','edier.acevedo.talentotech@usa.edu.co','M','3104667164'))
    insert_estudiante(conn, ('Jesika Tatiana','Correa Diaz','jesika.correa.talentotech@usa.edu.co','F','3105697387'))
    insert_estudiante(conn, ('Alejandro','Enciso Ramirez','alejandro.enciso.talentotech@usa.edu.co','M','3023269472'))
    insert_estudiante(conn, ('Luis Antonio','Cruz García','luis.cruz01.talentotech@usa.edu.co','M','3108698405'))
    insert_estudiante(conn, ('Yuri Carolina','Beltrán Jabonero','yuri.beltran01.talentotech@usa.edu.co','F','3214015682'))
    insert_estudiante(conn, ('Ana Carolina','Susa Triana','ana.susa.talentotech@usa.edu.co','F','3222475448'))
    insert_estudiante(conn, ('Juan Camilo','Sarmiento Ardila','juan.sarmiento.talentotech@usa.edu.co','M','3138412475'))
    insert_estudiante(conn, ('Julián Santiago','Barrera Lopez','julian.barrera.talentotech@usa.edu.co','M','3206269012'))
    insert_estudiante(conn, ('Alexandra','Silva','leidy.silva.talentotech@usa.edu.co','F','3213333686'))
    insert_estudiante(conn, ('Nancy Angélica','Salamanca Marentes','nancy.salamanca.talentotech@usa.edu.co','F','3114942313'))
    insert_estudiante(conn, ('Sergio Andres','Rodriguez Reyes','sergio.rodriguez.talentotech@usa.edu.co','M','3227611839'))
    insert_estudiante(conn, ('Javier','Martínez','victor.martinez01.talentotech@usa.edu.co','M','3243967311'))
    insert_estudiante(conn, ('Juan David','Toca Caro','juan.toca.talentotech@usa.edu.co','M','3155878782'))
    insert_estudiante(conn, ('Yuri Priscila','López Araque','yuri.lopez01.talentotech@usa.edu.co','F','3133360536'))
    insert_estudiante(conn, ('Juan David','Gomez Pinto','juan.gomez06.talentotech@usa.edu.co','M','3125788368'))
    insert_estudiante(conn, ('Maira Lorena','Martinez Sinning','maira.martinez.talentotech@usa.edu.co','F','3142938068'))
    insert_estudiante(conn, ('Lorena','Tibaduiza','lorena.tibaduiza.talentotech@usa.edu.co','F','3208039724'))
    insert_estudiante(conn, ('Santiago Alejandro','Pérez Amaya','santiago.perez.talentotech@usa.edu.co','M','3124352542'))
    insert_estudiante(conn, ('Sergio Alexander','Duarte González','sergio.duarte.talentotech@usa.edu.co','M','3023450050'))
    insert_estudiante(conn, ('Lady','Vargas','lady.vargas.talentotech@usa.edu.co','F','3184472253'))
    insert_estudiante(conn, ('Óscar Alejandro','Rodríguez Martínez','oscar.rodriguez02.talentotech@usa.edu.co','M','3108036747'))
    insert_estudiante(conn, ('Katherin Natalia','Vargas Soto','katherin.vargas.talentotech@usa.edu.co','F','3195553676'))
    insert_estudiante(conn, ('Shania','Leon','shania.leon.talentotech@usa.edu.co','F','3142780055'))
    insert_estudiante(conn, ('Yolima Andrea','Salcedo Perez','yolima.salcedo.talentotech@usa.edu.co','F','3112634805'))
    insert_estudiante(conn, ('Franklin Farid','Marroquin Leon','franklin.marroquin.talentotech@usa.edu.co','M','3185684135'))

